// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inooovdrycdmboaghdqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlub29vdmRyeWNkbWJvYWdoZHF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1ODc3NjIsImV4cCI6MjA2NTE2Mzc2Mn0.I9JAclsZdNmlLHe9zzt84ALPpKbonMZkkTSI9AlpYG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);